// This is autogenerated file. Do not edit!

package models.autogenerated;

class Posts
{
	var db : orm.Db;
	var orm : models.Orm;
	public var id : String;
	public var post : String;

	public function new(db:orm.Db, orm:models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(post:String) : Void
	{
		this.post = post;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `posts` SET '
				+  '`post` = ' + db.quote(post)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}