package models;

import models.Loginkey;

class LoginkeyManager extends models.autogenerated.LoginkeyManager
{
  override public function delete(key:String) : Void
  	{
  		db.query('DELETE FROM `loginkey` WHERE `key` = ' + db.quote(key));
  	}
}
