package models;

import models.Posts;

class PostsManager extends models.autogenerated.PostsManager
{
  override public function delete(id:String) : Void
    {
      db.query('DELETE FROM `posts` WHERE `id` = ' + db.quote(id));
    }
}
