package models;

import models.PostsInfo;

class PostsInfoManager extends models.autogenerated.PostsInfoManager
{
  override public function delete(id:String) : Void
    {
      db.query('DELETE FROM `posts_info` WHERE `id` = ' + db.quote(id));
    }
}
