package models;

class PostsInfo extends models.autogenerated.PostsInfo
{
  override public function save() : Void
  	{
  		db.query(
  			 'UPDATE `posts_info` SET '
  				+  '`title` = ' + db.quote(title)
  				+', `subtitle` = ' + db.quote(subtitle)
  				+', `overview` = ' + db.quote(overview)
  				+', `author_id` = ' + db.quote(author_id)
  				+', `publish_date` = ' + db.quote(publish_date)
  				+', `edit_date` = ' + db.quote(edit_date)
  				+', `day_popularity` = ' + db.quote(day_popularity)
  				+', `total_popularity` = ' + db.quote(total_popularity)
  				+', `last_access` = ' + db.quote(last_access)
  			  +' WHERE `id` = ' + db.quote(id)
  		);
  	}
}
